# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: backend-workflow

on:
  push:
    branches:
      - 'main'
      - 'backend'

jobs:
  run-commands-on-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: setup ssh
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.PRIVATEKEY }}
        exclude: |
          **/files/**
    - name: run commands to ec2 instance
      run:
        ssh -i $SSH_AUTH_SOCK -o StrictHostKeyChecking=no ubuntu@3.9.96.120 "cd /data/oramsys/backend && git pull && npm i -f && pm2 restart 0" 
      
