# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Frontend-workflow

on:
  push:
    branches:
      - 'main'
      - 'devops'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup working directory
        working-directory: frontend
        run: ls -ll
      - name: run build command
        working-directory: frontend
        run: | 
            ls -ll
            npm i -f 
            CI=false npm run build 
            ls -ll
      - name: Deploy stage
        run: |
          ls -ll
          cd frontend/build
          aws s3 sync . s3://oramsys.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETKEY }}
          AWS_DEFAULT_REGION: "us-east-1"
